// search and show
export const ACTIVE_SEARCH_PEOPLE = 'ACTIVE_SEARCH_PEOPLE';
export const SET_SEARCH_KEYWORDS = 'SET_SEARCH_KEYWORDS';
export const SEARCH_PEOPLE = 'SEARCH_PEOPLE';
export const SELECT_SEARCHED_PEOPLE = 'SELECT_SEARCHED_PEOPLE';
export const SHOW_PEOPLE_DETAIL = 'SHOW_PEOPLE_DETAIL';
export const UPDATE_CURRENT_PEOPLE_INDEX = 'UPDATE_CURRENT_PEOPLE_INDEX';

export const SHOW_PARENT = 'SHOW_PARENT';
export const SHOW_CHILDREN = 'SHOW_CHILDREN';
export const CREATE_PEOPLE = 'CREATE_PEOPLE';
export const UPDATE_PEOPLE = 'UPDATE_PEOPLE';
export const SEARCHING_PEOPLE = 'SEARCHING_PEOPLE';

export const GET_CHILDREN_BY_ID = 'GET_CHILDREN_BY_ID';

// weixin
export const GET_WEIXIN_INFO = 'GET_WEIXIN_INFO';
export const UPDATE_WEIXIN = 'UPDATE_WEIXIN';
