// search and show
export const SET_SEARCH_KEYWORDS = 'SET_SEARCH_KEYWORDS';
export const SEARCH_PEOPLE = 'SEARCH_PEOPLE';
export const SELECT_SEARCHED_PEOPLE = 'SELECT_SEARCHED_PEOPLE';

export const SHOW_PARENT = 'SHOW_PARENT';
export const SHOW_CHILDREN = 'SHOW_CHILDREN';
export const CREATE_PEOPLE = 'CREATE_PEOPLE';
export const UPDATE_PEOPLE = 'UPDATE_PEOPLE';
export const DELETE_PEOPLE = 'DELETE_PEOPLE';
export const GET_MY_MAP = 'GET_MY_MAP';
export const GET_MY_NODES = 'GET_MY_NODES';
export const SEARCHING_PEOPLE = 'SEARCHING_PEOPLE';

export const GET_CHILDREN_BY_ID = 'GET_CHILDREN_BY_ID';
export const GET_USER_INFO_BY_ID = 'GET_USER_INFO_BY_ID';

// weixin
export const GET_WEIXIN_INFO = 'GET_WEIXIN_INFO';
export const UPDATE_WEIXIN = 'UPDATE_WEIXIN';
